### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by bot101** [xtianus79/multiple-date-picker-angular#12]
This project's documentation is misleading and doesn't work at all.

**Comment by barrct** [comment]
Module file should be
import {MultipleDatePickerModule} from 'multiple-date-picker-angular';

@NgModule({
	imports: [
        MultipleDatePickerModule
	],
	declarations: [MyComponent]
})

**Comment by xtianus79** [comment]
@barrct are you interested in helping with this repo. I built this for a project and see that it needs maintained properly now. Everything works I am 100% if it works on Angular 8 vs Angular 2 which when I started this it was Angular 2.
