### ISSUE TITLE
highlight days not working

### ISSUE THREAD

**Issue by arunw3** [xtianus79/multiple-date-picker-angular#8]
I'm trying to highlight days but it is not getting highlighted, there are no console errors.
Below is my code for highlighting the day's. Please let me know what is wrong in my code
**AppComponent**
```javascript
import { Component, OnInit, Input, AfterViewInit, ViewChild } from '@angular/core';
import * as moment from 'moment/moment';
@Component({
  selector: 'app-root',
  template: `<multiple-date-picker [highlightDays]="highlightDays"></multiple-date-picker>`,
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit{
  highlightDays: any[]; 
  ngOnInit() 
  {
    this.highlightDays = [
      {date: moment().date(12).valueOf(), css: 'holiday', selectable: false, title: 'Holiday time !'},
      {date: moment().date(25).valueOf(), css: 'off', selectable: false, title: 'We don\'t work today'},
      {date: moment().date(30).valueOf(), css: 'birthday', selectable: true, title: 'I\'m thir... i\'m 28, seriously, I mean ...'}
   ];
  }
}
```
**AppModule**
```javascript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule} from '@angular/forms';
import { AppComponent } from './app.component';
import { MultipleDatePickerModule } from 'multiple-date-picker-a2';
@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    FormsModule,
    MultipleDatePickerModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by xtianus79** [comment]
why are you not importing this? 

      import { MultipleDatePicker, DateRangeHelper } from '../multiple-date-picker/index';

**Comment by arunw3** [comment]
Even with that it is not working.

**Comment by xtianus79** [comment]
what version of angular are you using?

**Comment by arunw3** [comment]
I'm using 4.4.6

**Comment by xtianus79** [comment]
ok if there are no errors... how about checking the css in the console to make sure the tags for that date have the correct tagging.... if they do then see if a color is being loaded for that new tag.  let me know if that is what the issue is

**Comment by arunw3** [comment]
after updating the plugin to 3.0.0 it started to work 👍 . 
Also is there any property to disable the user selection for the entire calendar?

**Comment by xtianus79** [comment]
@arunw3 I don't believe so but I can see the utility is warranted.  Also, there are other ways to achieve this through the interface.  i'll look into it.
